import { dashboardApi, getSelectedGuildId, setSelectedGuildId } from '../assets/js/dashboardApi.js';
import { getStoredSession, logoutFromDashboard } from '../assets/js/DiscordOAuth.js';

const $ = (s, root = document) => root.querySelector(s);
const content = $('#content');
const state = { guilds: [], guild: null, resources: { channels: [], roles: [] }, user: null, view: new URLSearchParams(location.search).get('view') || 'overview' };
const titles = { overview:'Overview', moderation:'Moderation', security:'Security & Antinuke', members:'Members', audit:'Audit Log', welcome:'Welcome & Roles', tickets:'Tickets', leveling:'Leveling', 'reaction-roles':'Reaction Roles', giveaways:'Giveaways', analytics:'Analytics', embeds:'Embed Builder', automation:'Automation', ai:'AI Assistant', integrations:'Integrations', 'server-config':'Server Configuration', settings:'Dashboard Settings' };

function esc(value=''){ return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function iconUrl(g){ return g?.icon ? `https://cdn.discordapp.com/icons/${g.id}/${g.icon}.png?size=128` : null; }
function selectedConfig(){ return state.guild?.config || {}; }
function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),2600); }
function setStatus(ok, text){ const el=$('#apiStatus'); el.textContent=text; el.className=`status-pill ${ok?'good':'bad'}`; }
function channelOptions(value=null){ return `<option value="">Not configured</option>${state.resources.channels.filter(c=>[0,2,5].includes(Number(c.type))).map(c=>`<option value="${esc(c.id)}" ${c.id===value?'selected':''}># ${esc(c.name)}</option>`).join('')}`; }
function roleOptions(value=null){ return `<option value="">Not configured</option>${state.resources.roles.filter(r=>!r.managed).map(r=>`<option value="${esc(r.id)}" ${r.id===value?'selected':''}>${esc(r.name)}</option>`).join('')}`; }
function toggle(label, description, path, checked){ return `<div class="row"><div class="row-main"><strong>${esc(label)}</strong><span>${esc(description)}</span></div><button class="switch ${checked?'on':''}" data-toggle="${esc(path)}" aria-label="Toggle ${esc(label)}"></button></div>`; }
function getPath(obj,path){ return path.split('.').reduce((v,k)=>v?.[k],obj); }
async function savePatch(patch, message='Saved'){ if(!state.guild) return; try{ const result=await dashboardApi.updateConfig(state.guild.id,patch); state.guild.config=result; toast(message); render(); }catch(e){ toast(e.message); } }

async function boot(){
  const session=getStoredSession();
  if(!session?.authenticated || !session.sessionToken){ location.href='../'; return; }
  try{
    state.user=(await dashboardApi.me()).user;
    state.guilds=(await dashboardApi.guilds()).guilds || [];
    const preferred=getSelectedGuildId();
    let candidate=state.guilds.find(g=>g.id===preferred && g.botPresent) || state.guilds.find(g=>g.botPresent);
    if(!candidate){ setStatus(false,'No managed server'); renderNoServer(); return; }
    await selectGuild(candidate.id,false);
    setStatus(true,'API connected');
  }catch(e){ setStatus(false,'API error'); content.innerHTML=`<div class="card"><h2>Dashboard could not load</h2><p>${esc(e.message)}</p><button class="btn primary" id="retry">Retry</button></div>`; $('#retry').onclick=boot; }
}
async function selectGuild(id, rerender=true){
  const data=await dashboardApi.guild(id); state.guild=data.guild; setSelectedGuildId(id);
  state.resources=await dashboardApi.resources(id);
  $('#serverName').textContent=state.guild.name; $('#profileName').textContent=state.user?.global_name || state.user?.username || 'Account';
  const av=state.user?.avatar; if(av) $('#avatarFallback').innerHTML=`<img src="https://cdn.discordapp.com/avatars/${state.user.id}/${av}.png?size=64" style="width:100%;height:100%;border-radius:50%" alt="">`;
  if(rerender) render();
}
function renderNoServer(){ content.innerHTML=`<div class="card empty"><h2>NyxEclypse is not installed anywhere you can manage.</h2><p>Install the bot into a server you manage, then return here.</p><a class="btn primary" href="../pages/invite.html">Invite NyxEclypse</a></div>`; }

function render(){
  const view=state.view; $('#viewTitle').textContent=titles[view]||'Overview'; document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===view));
  const renderers={overview:overview,moderation:moderation,security:security,members:members,audit:audit,welcome:welcome,tickets:tickets,leveling:leveling,'reaction-roles':reactionRoles,giveaways:giveaways,analytics:analytics,embeds:embeds,automation:automation,ai:ai,integrations:integrations,'server-config':serverConfig,settings:settings};
  content.innerHTML=(renderers[view]||overview)(); bindView();
}
function baseHero(kicker,title,description,actions=''){ return `<div class="hero"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="actions">${actions}</div></div>`; }
function stat(label,value,sub=''){ return `<div class="card stat-card"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(sub)}</span></div>`; }

function overview(){ const g=state.guild,c=g.config||{},l=g.logging||{}; return baseHero('Server control center',`Welcome back, ${state.user?.global_name||state.user?.username||'admin'}`,`${g.name} is connected to NyxEclypse. Configure every major module from one place.`,'<button class="btn primary" data-action="refresh">↻ Refresh data</button>')+`<div class="grid stats">${stat('Members',g.memberCount,'Server members')}${stat('Humans',g.humanCount,'Non-bot members')}${stat('Channels',g.channels,'Cached channels')}${stat('Roles',g.roles,'Server roles')}</div><div class="grid two" style="margin-top:14px"><div class="card"><div class="section-title"><h2>Module control</h2><span>${Object.keys(c).length} config groups</span></div><div class="list">${toggle('Moderation','Case history and moderation configuration','moderation.enabled',c.moderation?.enabled!==false)}${toggle('Security','Anti-raid and protection controls','security.enabled',c.security?.enabled!==false)}${toggle('Welcome','Welcome messaging and autorole','welcome.enabled',c.welcome?.enabled!==false)}${toggle('Tickets','Ticket workflow configuration','tickets.enabled',c.tickets?.enabled!==false)}${toggle('Leveling','XP and level role configuration','leveling.enabled',c.leveling?.enabled!==false)}</div></div><div class="card"><div class="section-title"><h2>Logging</h2><span class="tag ${l.enabled?'good':''}">${l.enabled?'Enabled':'Disabled'}</span></div><p class="notice">Audit logging is wired to the bot's logging service. Select its channels from Server Configuration.</p><div class="row"><div class="row-main"><strong>Audit channel</strong><span>${esc(l.channels?.audit ? channelName(l.channels.audit) : 'Not configured')}</span></div><span class="tag">${l.channels?.audit?'configured':'setup needed'}</span></div><div class="row"><div class="row-main"><strong>Verification</strong><span>Server verification panel</span></div><span class="tag">${c.verification?.enabled?'enabled':'disabled'}</span></div></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Control surface</h2><span>GuildNexus</span></div><div class="grid module-grid">${module('⚖','Moderation','Warnings, cases, filters and enforcement','moderation')}${module('◈','Security','Anti-raid, lockdown and protection','security')}${module('▣','Tickets','Support queues and workflows','tickets')}${module('◒','Analytics','Server growth and activity','analytics')}${module('▧','Embeds','Build rich Discord messages','embeds')}${module('⚙','Automation','Scripts, aliases and scheduled actions','automation')}</div></div>`; }
function channelName(id){ return state.resources.channels.find(c=>c.id===id)?.name || id; }
function module(ic,title,desc,view){ return `<button class="card module" data-nav="${view}" style="text-align:left;color:inherit"><div class="icon">${ic}</div><h3>${title}</h3><p>${desc}</p><span class="tag">Open module →</span></button>`; }

function moderation(){ const c=selectedConfig(); return baseHero('Safety','Moderation','Manage moderation posture, case logging, roles and audit destinations.')+`<div class="grid two"><div class="card"><div class="section-title"><h2>Moderation controls</h2></div>${toggle('Moderation enabled','Allow NyxEclypse moderation systems to operate','moderation.enabled',c.moderation?.enabled!==false)}${toggle('Auto moderation','Message and content filtering','moderation.automod',c.moderation?.automod===true)}${toggle('Escalation logging','Record enforcement in moderation cases','moderation.caseLogging',c.moderation?.caseLogging!==false)}</div><div class="card"><div class="section-title"><h2>Moderator roles</h2></div><div class="field"><label>Moderator role</label><select data-config="modRole">${roleOptions(c.modRole)}</select></div><div class="field"><label>Admin role</label><select data-config="adminRole">${roleOptions(c.adminRole)}</select></div><button class="btn primary" data-action="save-fields">Save roles</button></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Recent cases</h2><span>Live from NyxEclypse</span></div><div id="caseTable" class="empty">Loading cases…</div></div>`; }
function security(){ const c=selectedConfig(); return baseHero('Protection','Security & Antinuke','Centralize raid protection, lockdown behavior and dangerous permission safeguards.')+`<div class="grid three"><div class="card">${toggle('Protection enabled','Global security module','security.enabled',c.security?.enabled!==false)}${toggle('Anti-raid','Detect abnormal join bursts','security.antiraid',c.security?.antiraid===true)}${toggle('Lockdown','Restrict server during incidents','security.lockdown',c.security?.lockdown===true)}</div><div class="card"><div class="section-title"><h3>Security posture</h3></div><div class="field"><label>Join threshold</label><input type="number" min="1" value="${esc(c.security?.joinThreshold||10)}" data-config="security.joinThreshold"></div><div class="field"><label>Raid action</label><select data-config="security.raidAction"><option>notify</option><option>kick</option><option>lockdown</option></select></div><button class="btn primary" data-action="save-fields">Save protection</button></div><div class="card"><h3>Permission safety</h3><p class="notice">Keep Administrator access limited. The dashboard only permits users Discord itself says can manage this server.</p><div class="row"><div class="row-main"><strong>Dashboard authorization</strong><span>Owner / Manage Server / Administrator</span></div><span class="tag good">enforced</span></div></div></div>`; }
function members(){ return baseHero('Community','Members','Inspect a member, account age, join date and roles.')+`<div class="card"><div class="form-grid"><div class="field"><label>Discord user ID</label><input id="memberId" inputmode="numeric" placeholder="123456789012345678"></div><div style="display:flex;align-items:end"><button class="btn primary" data-action="lookup-member">Look up member</button></div></div><div id="memberResult" class="empty">Enter a Discord user ID to inspect the member.</div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Server resources</h2><span>${state.resources.roles.length} roles · ${state.resources.channels.length} channels</span></div><div class="grid two"><div><h3>Roles</h3><div class="list">${state.resources.roles.slice(0,12).map(r=>`<div class="row"><div class="row-main"><strong>${esc(r.name)}</strong><span>Position ${r.position}</span></div><span class="tag">${r.managed?'managed':'editable'}</span></div>`).join('')}</div></div><div><h3>Channels</h3><div class="list">${state.resources.channels.slice(0,12).map(c=>`<div class="row"><div class="row-main"><strong># ${esc(c.name)}</strong><span>ID ${esc(c.id)}</span></div><span class="tag">type ${c.type}</span></div>`).join('')}</div></div></div></div>`; }
function audit(){ return baseHero('Transparency','Audit Log','Review events captured in the configured NyxEclypse audit channel.')+`<div class="card"><div class="section-title"><h2>Event stream</h2><button class="btn" data-action="load-audit">Refresh</button></div><div id="auditTable" class="empty">Loading audit events…</div></div>`; }
function welcome(){ const c=selectedConfig(); return baseHero('Onboarding','Welcome & Roles','Configure the first impression, welcome channel and automatic role assignment.')+`<div class="grid two"><div class="card">${toggle('Welcome messages','Send a welcome message for new members','welcome.enabled',c.welcome?.enabled!==false)}<div class="field"><label>Welcome channel</label><select data-config="welcomeChannel">${channelOptions(c.welcomeChannel)}</select></div><div class="field"><label>Automatic role</label><select data-config="autoRole">${roleOptions(c.autoRole)}</select></div></div><div class="card"><div class="field"><label>Welcome message</label><textarea data-config="welcomeMessage">${esc(c.welcomeMessage||'Welcome {user} to {server}!')}</textarea></div><div class="notice">Supported placeholders can be handled by the bot's existing welcome system. Keep messages concise enough for Discord's limits.</div><button class="btn primary" data-action="save-fields">Save welcome setup</button></div></div>`; }
function tickets(){ const c=selectedConfig(); return baseHero('Support','Tickets','Configure the ticket experience, notifications and support workflow.')+`<div class="grid three"><div class="card">${toggle('Tickets enabled','Enable ticket workflows','tickets.enabled',c.tickets?.enabled!==false)}${toggle('Auto assign','Assign new tickets to available staff','tickets.autoAssign',c.tickets?.autoAssign===true)}${toggle('Ratings','Collect close ratings','tickets.ratings',c.tickets?.ratings===true)}</div><div class="card"><div class="field"><label>Ticket category</label><select data-config="tickets.categoryId">${channelOptions(c.tickets?.categoryId)}</select></div><div class="field"><label>Transcript channel</label><select data-config="tickets.transcriptChannelId">${channelOptions(c.tickets?.transcriptChannelId)}</select></div><button class="btn primary" data-action="save-fields">Save ticket settings</button></div><div class="card"><h3>Workflow</h3><p class="notice">Claim profiles, priorities, notes, saved replies and case attachment can be exposed as the bot's ticket implementation grows. This dashboard keeps the configuration surface ready.</p></div></div>`; }
function leveling(){ const c=selectedConfig(); return baseHero('Engagement','Leveling','Control XP, announcements and level-role progression.')+`<div class="grid two"><div class="card">${toggle('Leveling enabled','Award XP for community activity','leveling.enabled',c.leveling?.enabled!==false)}${toggle('Announce levels','Post level-up notifications','leveling.announce',c.leveling?.announce!==false)}<div class="field"><label>XP per message</label><input type="number" min="0" value="${esc(c.leveling?.xpPerMessage||10)}" data-config="leveling.xpPerMessage"></div><button class="btn primary" data-action="save-fields">Save leveling</button></div><div class="card"><h3>Level role mapping</h3><p class="notice">Create level → role mappings in the bot configuration. The dashboard can then use this resource list to keep roles consistent.</p>${state.resources.roles.slice(0,8).map(r=>`<div class="row"><div class="row-main"><strong>${esc(r.name)}</strong><span>Role ID ${esc(r.id)}</span></div><span class="tag">position ${r.position}</span></div>`).join('')}</div></div>`; }
function reactionRoles(){ const c=selectedConfig(); return baseHero('Interactions','Reaction Roles','Manage self-assignable roles and interaction panels.')+`<div class="card"><div class="section-title"><h2>Reaction-role system</h2><span>Configuration workspace</span></div>${toggle('Reaction roles enabled','Allow configured role panels','reactionRoles.enabled',c.reactionRoles?.enabled!==false)}<div class="notice" style="margin-top:12px">Existing reaction-role handlers remain the source of truth for actual Discord interactions. Use this page as the centralized configuration surface rather than duplicating role state in the browser.</div></div><div class="card" style="margin-top:14px"><h3>Available roles</h3><div class="grid three">${state.resources.roles.filter(r=>!r.managed).slice(0,18).map(r=>`<div class="card"><strong>${esc(r.name)}</strong><p style="color:var(--muted);font-size:10px">${esc(r.id)}</p></div>`).join('')}</div></div>`; }
function giveaways(){ return baseHero('Events','Giveaways','Monitor the giveaway system and keep the dashboard ready for scheduling and management.')+`<div class="grid three"><div class="card"><h3>Giveaway engine</h3><p class="notice">NyxEclypse already runs scheduled giveaway checks. Persistent giveaway management requires the PostgreSQL database to be available.</p><span class="tag warn">Database dependent</span></div><div class="card"><h3>Scheduling</h3><p class="notice">Use the bot's existing giveaway commands for creation until dashboard write endpoints are exposed.</p></div><div class="card"><h3>Persistence</h3><p class="notice">If PostgreSQL is unavailable, giveaway state can be lost when the process restarts.</p></div></div>`; }
function analytics(){ const g=state.guild; return baseHero('Insights','Analytics','A clean analytics surface for membership, activity and growth metrics.')+`<div class="grid stats">${stat('Members',g.memberCount,'Current snapshot')}${stat('Human members',g.humanCount,'Current snapshot')}${stat('Bots',g.botCount,'Current snapshot')}${stat('Channels',g.channels,'Current snapshot')}</div><div class="card" style="margin-top:14px"><h2>Historical analytics</h2><p class="notice">Historical message, reaction, voice and membership charts require persisted event counters. The current bot exposes server counters, but this dashboard does not invent historical values when the backend has not collected them.</p><div class="bar" style="margin-top:15px"><i style="width:100%"></i></div><p style="font-size:10px;color:var(--muted)">Current snapshot available · historical series pending telemetry storage</p></div>`; }
function embeds(){ return baseHero('Builder','Embed Builder','Compose rich Discord embeds before wiring them into a bot delivery action.')+`<div class="grid two"><div class="card"><div class="field"><label>Title</label><input id="embedTitle" placeholder="Announcement"></div><div class="field"><label>Description</label><textarea id="embedDesc" placeholder="Write your message…"></textarea></div><div class="form-grid"><div class="field"><label>Color</label><input id="embedColor" value="#8b5cf6"></div><div class="field"><label>Footer</label><input id="embedFooter" placeholder="GuildNexus"></div></div><button class="btn primary" data-action="preview-embed">Update preview</button></div><div class="card"><div class="section-title"><h2>Preview</h2><span>Local builder</span></div><div id="embedPreview" class="notice">Your embed preview will appear here.</div><button class="btn" style="margin-top:10px" data-action="copy-embed">Copy JSON</button></div></div>`; }
function automation(){ return baseHero('Automation','Automation & Custom Scripts','Centralize aliases, scheduled jobs and reusable automation definitions.')+`<div class="grid three"><div class="card">${toggle('Automation','Enable automation module','automation.enabled',true)}<p class="notice">Use server configuration as the durable source. Browser-only scripts are never executed automatically.</p></div><div class="card"><h3>Command aliases</h3><p class="notice">Define reusable command shortcuts once the corresponding bot-side alias storage is enabled.</p><button class="btn" data-action="save-note">Save workspace note</button></div><div class="card"><h3>Custom scripts</h3><p class="notice">Scripts should execute server-side with explicit permission checks, rate limits and a sandbox. The dashboard never runs arbitrary JavaScript.</p></div></div>`; }
function ai(){ return baseHero('Assistant','AI Assistant','A dedicated space for AI-powered server tooling without pretending the browser is a secure AI backend.')+`<div class="grid two"><div class="card"><h2>Ask GuildNexus</h2><div class="field"><label>Prompt</label><textarea id="aiPrompt" placeholder="Summarize the moderation posture for this server…"></textarea></div><button class="btn primary" data-action="ai-local">Generate draft</button></div><div class="card"><h2>Response</h2><div id="aiResult" class="notice">AI requests need a configured server-side provider. This UI intentionally does not expose API keys in the browser.</div></div></div>`; }
function integrations(){ return baseHero('Connections','Integrations','Connect community services and keep their configuration in one place.')+`<div class="grid module-grid">${module('◉','Discord','OAuth and guild authorization are active','settings')}${module('▶','YouTube','Feed notifications workspace','integrations')}${module('♪','Twitch','Stream notification workspace','integrations')}${module('◈','TikTok','Social notification workspace','integrations')}${module('⌂','GitHub','Repository notification workspace','integrations')}${module('◎','Webhooks','Webhook destinations and event routing','server-config')}</div>`; }
function serverConfig(){ const c=selectedConfig(),l=c.logging||{}; return baseHero('System','Server Configuration','Edit the bot configuration shared by all GuildNexus modules.')+`<div class="grid two"><div class="card"><div class="field"><label>Command prefix</label><input data-config="prefix" value="${esc(c.prefix||'!')}"></div><div class="field"><label>Birthday channel</label><select data-config="birthdayChannelId">${channelOptions(c.birthdayChannelId)}</select></div><div class="field"><label>Welcome channel</label><select data-config="welcomeChannel">${channelOptions(c.welcomeChannel)}</select></div><div class="field"><label>Auto role</label><select data-config="autoRole">${roleOptions(c.autoRole)}</select></div><button class="btn primary" data-action="save-fields">Save server configuration</button></div><div class="card"><div class="section-title"><h2>Logging</h2><span>${l.enabled?'enabled':'disabled'}</span></div>${toggle('Logging enabled','Write configured events to the audit system','logging.enabled',l.enabled===true)}<div class="field"><label>Audit channel</label><select data-config="logging.channels.audit">${channelOptions(l.channels?.audit)}</select></div><div class="field"><label>Application channel</label><select data-config="logging.channels.applications">${channelOptions(l.channels?.applications)}</select></div><div class="field"><label>Reports channel</label><select data-config="logging.channels.reports">${channelOptions(l.channels?.reports)}</select></div><button class="btn primary" data-action="save-fields">Save logging</button></div></div>`; }
function settings(){ return baseHero('Preferences','Dashboard Settings','Local preferences for the GuildNexus control center.')+`<div class="grid two"><div class="card">${toggle('Compact navigation','Use tighter dashboard spacing','ui.compact',localStorage.getItem('gn_compact')==='1')}${toggle('Remember server','Keep the selected server between visits','ui.rememberGuild',localStorage.getItem('gn_remember')!=='0')}${toggle('Reduce motion','Disable most dashboard transitions','ui.reduceMotion',localStorage.getItem('gn_motion')==='1')}</div><div class="card"><h3>Account</h3><div class="row"><div class="row-main"><strong>${esc(state.user?.global_name||state.user?.username||'Discord user')}</strong><span>${esc(state.user?.id||'')}</span></div><span class="tag good">authenticated</span></div><button class="btn" data-action="logout" style="margin-top:12px">Sign out</button></div></div>`; }

async function bindView(){
  document.querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>navigate(el.dataset.nav));
  document.querySelectorAll('[data-toggle]').forEach(el=>el.onclick=async()=>{ const path=el.dataset.toggle; const current=getPath(selectedConfig(),path); const value=!Boolean(current); if(path.startsWith('ui.')){ localStorage.setItem(path==='ui.compact'?'gn_compact':path==='ui.rememberGuild'?'gn_remember':'gn_motion',value?'1':'0'); render(); return; } await savePath(path,value); });
  document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>actions(el.dataset.action));
  if(state.view==='moderation') loadCases(); if(state.view==='audit') loadAudit();
}
async function savePath(path,value){ const parts=path.split('.'); if(parts.length===1) return savePatch({[parts[0]]:value}); let patch={}; let cursor=patch; for(let i=0;i<parts.length-1;i++){ cursor[parts[i]]={}; cursor=cursor[parts[i]]; } cursor[parts.at(-1)]=value; await savePatch(patch,'Setting saved'); }
function collectFields(){ const patch={}; document.querySelectorAll('[data-config]').forEach(el=>{ const path=el.dataset.config.split('.'); let cursor=patch; for(let i=0;i<path.length-1;i++){ cursor[path[i]]=cursor[path[i]]||{}; cursor=cursor[path[i]]; } cursor[path.at(-1)]=el.value||null; }); return patch; }
async function actions(action){
  if(action==='refresh'){ await selectGuild(state.guild.id); toast('Server data refreshed'); }
  if(action==='save-fields'){ await savePatch(collectFields(),'Configuration saved'); }
  if(action==='lookup-member'){ const id=$('#memberId')?.value.trim(); if(!id) return toast('Enter a Discord user ID.'); try{ const m=(await dashboardApi.member(state.guild.id,id)).member; $('#memberResult').innerHTML=`<div class="row"><div class="row-main"><strong>${esc(m.globalName||m.username)}</strong><span>@${esc(m.username)} · ${m.bot?'Bot':'User'}</span></div><span class="tag">${esc(m.id)}</span></div><div class="grid three" style="margin-top:10px">${stat('Joined',new Date(m.joinedAt).toLocaleDateString(),'Server join date')}${stat('Account',new Date(m.accountCreatedAt).toLocaleDateString(),'Account creation')}${stat('Roles',m.roles.length,'Assigned roles')}</div><div class="notice" style="margin-top:12px">Roles: ${m.roles.map(r=>esc(r.name)).join(', ')||'@everyone'}</div>`; }catch(e){ $('#memberResult').textContent=e.message; } }
  if(action==='load-audit') loadAudit();
  if(action==='preview-embed'){ const t=$('#embedTitle').value,d=$('#embedDesc').value,f=$('#embedFooter').value,c=$('#embedColor').value; $('#embedPreview').style.borderLeft=`4px solid ${c}`; $('#embedPreview').innerHTML=`<strong>${esc(t||'Untitled')}</strong><p>${esc(d||'No description')}</p><small>${esc(f)}</small>`; }
  if(action==='copy-embed'){ const data={title:$('#embedTitle')?.value||'',description:$('#embedDesc')?.value||'',color:$('#embedColor')?.value||'',footer:$('#embedFooter')?.value||''}; await navigator.clipboard?.writeText(JSON.stringify(data,null,2)); toast('Embed JSON copied'); }
  if(action==='ai-local'){ const p=$('#aiPrompt').value.trim(); $('#aiResult').textContent=p?`Draft prepared for: ${p}\n\nConnect a server-side AI provider to turn this draft surface into a live assistant.`:'Enter a prompt first.'; }
  if(action==='logout'){ await logoutFromDashboard(); location.href='../'; }
  if(action==='save-note'){ localStorage.setItem(`gn_note_${state.guild.id}`,new Date().toISOString()); toast('Workspace note saved locally'); }
}
async function loadCases(){ try{ const data=await dashboardApi.cases(state.guild.id,{limit:25}); const cases=data.cases||data; $('#caseTable').innerHTML=cases.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Action</th><th>User</th><th>Moderator</th><th>Created</th></tr></thead><tbody>${cases.map(x=>`<tr><td><span class="tag">${esc(x.action||x.type||'case')}</span></td><td>${esc(x.userId||x.targetId||'unknown')}</td><td>${esc(x.moderatorId||'unknown')}</td><td>${esc(x.createdAt?new Date(x.createdAt).toLocaleString():'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No moderation cases found.</div>'; }catch(e){ $('#caseTable').textContent=e.message; } }
async function loadAudit(){ try{ const data=await dashboardApi.auditLog(state.guild.id,{limit:50}); const events=data.events||[]; $('#auditTable').innerHTML=events.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Time</th><th>Event</th><th>Source</th></tr></thead><tbody>${events.map(e=>`<tr><td>${esc(new Date(e.createdAt).toLocaleString())}</td><td>${esc(e.embed?.title||e.content||'Audit event')}</td><td><a href="${esc(e.url)}" target="_blank" rel="noreferrer">Open message</a></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">${data.enabled?'No events found in the audit channel.':'Audit logging is not configured.'}</div>`; }catch(e){ $('#auditTable').textContent=e.message; } }
function navigate(view){ state.view=view; history.pushState({},'',`?view=${encodeURIComponent(view)}`); render(); document.querySelector('#sidebar')?.classList.remove('open'); }

$('#serverMenuBtn').onclick=()=>{ $('#serverModal').classList.remove('hidden'); $('#serverList').innerHTML=state.guilds.map(g=>`<button class="server-option" data-server="${g.id}"><span class="server-icon">${iconUrl(g)?`<img src="${iconUrl(g)}" alt="">`:'N'}</span><span><strong>${esc(g.name)}</strong><br><small style="color:var(--muted)">${g.botPresent?'NyxEclypse installed':'Bot not installed'}</small></span></button>`).join(''); document.querySelectorAll('[data-server]').forEach(b=>b.onclick=async()=>{ try{await selectGuild(b.dataset.server); $('#serverModal').classList.add('hidden');}catch(e){toast(e.message)} });};
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('#serverModal').classList.add('hidden'));
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#refreshBtn').onclick=()=>actions('refresh');
$('#logoutBtn').onclick=()=>actions('logout');
window.onpopstate=()=>{state.view=new URLSearchParams(location.search).get('view')||'overview';render()};
boot();
